version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "makeitstrict"
    commit-message:
      prefix: "[actions] "
